version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
        - 9443:9443
    volumes:
      - ./volumes/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  node-red:
    build: ./services/nodered/.
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880" 
    volumes:
      - ./volumes/data:/data
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    user: "1883"
    ports:
      - 1883:1883
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config 
    restart: always

  influxdb:
    image: influxdb:2.6
    ports: 
      - 8086:8086
    volumes: 
      - ./volumes/influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana:8.2.6
    ports:
      - 3000:3000
    volumes: 
      - ./volumes/grafana:/var/lib/grafana
    restart: always